# -*- coding: utf-8 -*-
"""

Author: Xiaofeng Liu, PhD, PE
Penn State University
"""

import sys
import numpy as np
import h5py
import meshio
from scipy import interpolate
from osgeo import gdal

class SRH_2D_Data:
    """
    A class for SRH-2D data I/O, manipulation, and format conversion
    
    This class is designed to read SRH-2D results in format other than VTK. It can 
    save SRH-2D results into VTK format for visualization in Paraview, parse
    SRH-2D mesh information and convert/save to other formats, query SRH-2D
    results (e.g., for calibration), etc.
    
    Attributes
    ----------
    hdf_filename : str
        the name for the HDF result file generated by HEC-RAS
    
    
    Methods
    -------
    get_units()    
        Get the units used in the SRH-2D project
    
    """
    
    def __init__(self, srh_filename, terrain_filename):
        self.srh_filename = srh_filename
        self.terrain_filename = terrain_filename




#testing
def main():
    my_srh2d_data = SRH_2D_Data("Muncie2DOnly_SI.data","subterrain_exported.tif")

    print("All done!")

if __name__ == "__main__":
    main()
