"""
Perform Monte Carlo simulation with the SRH_2D_Model and SRH_2D_Data classes. It uses pyHMT2D to control the run of SRH-2D model, extract information, and parallelization.

The parameter values for the Monte Carlo simulation are read in from a file, which should be generated by the preprocessing script.
"""

#if run in the cloud, need to specify the location of pyHMT2D. If pyHMT2D is installed
#with regular pip install, then the following is not necessary.
#import sys
#sys.path.append(r"C:\Users\Administrator\python_packages\pyHMT2D")

import pyHMT2D

import numpy as np

import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter

import vtk
from vtk.numpy_interface import dataset_adapter as dsa

import multiprocessing
import os
import sys
import json
import platform
import time
from datetime import datetime

# Now import the SRH_2D_solver_module 
from SRH_2D_solver_module import run_one_SRH_2D_case

plt.rc('text', usetex=False)  #allow the use of Latex for math expressions and equations
plt.rc('font', family='serif') #specify the default font family to be "serif"


def Monte_Carlo_simulations_parallel(srhcontrol_file, samples, ManningN_MaterialIDs, ManningN_MaterialNames, nProcess, bDeleteCaseDir=True):
    """
    Run Monte Carlo simulations nSamples times. Run all cases in parallel using multiple CPU cores. Each core
    simulates one case at a time.

    In this example, only one inlet-q and one Manning's n is varied for a zone in the domain. For the exit-h boundary, a rating curve is used. Thus, there is no need to change anything for the exit-h boundary.

    Parameters
    ----------
    srhcontrol_file : str
        Name of the SRH-2D control file (either srhhydro or SIF file), e.g., "case_SIF.dat" or "case.srhhydro"
    samples : numpy array
        list of Manning's n values
    ManningN_MaterialIDs : list of int
        ID list of the Manning's n zones. Note: in HEC-RAS, the ID is 1-based.
    ManningN_MaterialNames : list of str
        Name list of the Manning's n zones
    nProcess : int
        number of parallel processes to use
    bDeleteCaseDir : bool
        whether to delete case directory when simulation is done. Default is True. If it is set to False, the case directory
        will be kept. However, be cautious on this. If the number of simulations is large, all cases together will use
        very large space on the hard disk.

        In this example, the simulation result is saved into a VTK file (thus the case directory is not needed after
        simulation is done).

    Returns
    -------

    """

    #print("Running Monte Carlo simulations in parallel with", nProcess, "processes ...")

    #number of samples
    nSamples = samples.shape[0]

    #access/set the parameter values
    Manning_n_samples = samples

    #make the directory "cases". If it already exists, reminder user that the contents within may be overwritten.
    if os.path.isdir("cases"):
        print("The directory cases already exists. The contents within may be overwritten.")
        #quit()
    else:
        os.mkdir("cases")

    #create the list of case IDs to be assigned to the parallel workers
    caseIDs = [*range(1, nSamples+1, 1)]    

    #prepare the arguments for calling the "run_one_SRH_2D_case(...)" function    
    #args: run_one_SRH_2D_case(case_ID, srhcontrol_file, ManningN_MaterialIDs, ManningNs, ManningN_MaterialNames, bDeleteCaseDir=True)
    args = [(caseID, srhcontrol_file, ManningN_MaterialIDs, [ManningN], ManningN_MaterialNames, bDeleteCaseDir) 
            for caseID, ManningN in zip(caseIDs, Manning_n_samples)]

    # do the work
    # Use maxtasksperchild=1 so each worker runs one case then exits. This avoids memory/state
    # accumulation from SRH-2D runs and reduces risk of OOM or incomplete output when many
    # cases run in parallel on Linux.
    with multiprocessing.Pool(processes=nProcess, maxtasksperchild=1) as pool:
        try:
            outputs = pool.starmap(run_one_SRH_2D_case, args)
            pool.close()
            pool.join()
        except Exception as e:
            pool.terminate()
            pool.join()
            # Worker death (OOM, segfault) often shows as BrokenProcessPool or similar
            if "BrokenProcessPool" in type(e).__name__ or "Process" in type(e).__name__:
                raise RuntimeError(
                    "A worker process died (e.g. out-of-memory or crash). "
                    "Reduce nProcess or run failed cases manually. Original: %s" % e
                ) from e
            raise e

    print("Parallel run of cases done.")

    # Count the number of successful and failed runs
    successful_runs = [output for output in outputs if output > 0]
    failed_runs = [output for output in outputs if output < 0]
    print("    Number of successful runs = ", len(successful_runs))
    print("    Number of failed runs = ", len(failed_runs))

    # save the returned outputs as a json file: outputs contains the caseIDs (positive if the case run was successful,
    # negative otherwise); also save successful and failed runs in the same json file
    # prepare the data to be saved
    date_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")    #take the current date and time
    output_filename = f'parallel_run_SRH_2D_outputs_{date_time}.json'
    data_to_save = {
        "nSamples": nSamples,
        "nSamples_successful": len(successful_runs),
        "nSamples_failed": len(failed_runs),
        "all_run_results": outputs,
        "successful_runs": successful_runs,
        "failed_runs": failed_runs
    }
    with open(output_filename, 'w') as f:
        json.dump(data_to_save, f, indent=4)

def Monte_Carlo_simulations_serial(srhcontrol_file, samples, ManningN_MaterialIDs, ManningN_MaterialNames, bDeleteCaseDir=True):
    """
    Run Monte Carlo simulations in serial

    Parameters
    ----------
    srhcontrol_file : str
        Name of the SRH-2D control file (either srhhydro or SIF file), e.g., "case_SIF.dat" or "case.srhhydro"
    samples : numpy array
        list of Manning's n values
    ManningN_MaterialIDs : list of int
        ID list of the Manning's n zones. Note: in SRH-2D, the ID is 1-based.
    ManningN_MaterialNames : list of str
        Name list of the Manning's n zones
    bDeleteCaseDir : bool
        whether to delete case directory when simulation is done. Default is True. If it is set to False, the case directory
        will be kept. However, be cautious on this. If the number of simulations is large, all cases together will use
        very large space on the hard disk.

    Returns
    -------

    """

    print("Running Monte Carlo simulations in serial ...")

    #number of samples
    nSamples = samples.shape[0]

    #access/set the parameter values
    Manning_n_samples = samples

    #make the directory "cases". If it already exists, reminder user that the contents within may be overwritten.
    if os.path.isdir("cases"):
        print("The directory cases already exists. The contents within may be overwritten.")
        #quit()
    else:
        os.mkdir("cases")

    #list to collect outputs
    outputs = []

    #for i in range(1, nSamples+1):   #run all cases in the sample file (case ID starts from 1)
    for i in range(1, 3):  #For debugging/testing, only run the first several cases
        print("    Running Monte Carlo simulation # ", i, "out of", nSamples)

        #access the parameter values
        ManningN = samples[i]

        print("ManningN = ", ManningN)

        #run_one_SRH_2D_case(case_ID, srhcontrol_file, ManningN_MaterialIDs, ManningN, ManningN_MaterialNames, bDeleteCaseDir=True)
        output = run_one_SRH_2D_case(i, srhcontrol_file, ManningN_MaterialIDs, [ManningN], ManningN_MaterialNames, bDeleteCaseDir)


        outputs.append(output)
    
    print("    Serial run of cases done.")    

    # Count the number of successful and failed runs
    successful_runs = [output for output in outputs if output > 0]
    failed_runs = [output for output in outputs if output < 0]
    print("    Number of successful runs = ", len(successful_runs))
    print("    Number of failed runs = ", len(failed_runs))

    # save the returned outputs as a json file: outputs contains the caseIDs (positive if the case run was successful,
    # negative otherwise); also save successful and failed runs in the same json file
    # prepare the data to be saved
    date_time = datetime.now().strftime("%Y_%m_%d-%I_%M_%S_%p")    #take the current date and time
    output_filename = f'serial_run_SRH_2D_outputs_{date_time}.json'
    data_to_save = {
        "nSamples": nSamples,
        "nSamples_successful": len(successful_runs),
        "nSamples_failed": len(failed_runs),
        "all_run_results": outputs,
        "successful_runs": successful_runs,
        "failed_runs": failed_runs
    }
    with open(output_filename, 'w') as f:
        json.dump(data_to_save, f, indent=4)


def postprocess_results(nSamples):
    """
    Postprocess the Monte Carlo simulation results, which are in the format of VTK files in "cases" directory.

    - Statistics at a given a point
    - Innundation map with certain confidence intervals

    Returns
    -------

    """

    #probe point location (hard-coded; need to change for a specific case)
    probe_x = 411100.0
    probe_y = 1.80345e+06

    #array to store the probed WSE at the probing point
    probed_WSE = np.zeros(nSamples)

    #array to store water depth field from all VTK files
    water_depth_all = None

    vtk_handler = pyHMT2D.Misc.vtkHandler()

    #loop over all VTK result files
    for i in range(nSamples):
        #VTK file name
        vtk_filename = "cases/case_"+str(i+1).zfill(6)+".vtk"

        print("Processing ", vtk_filename)

        #create VTK unstructured grid reader
        reader = vtk_handler.readVTK_UnstructuredGrid(vtk_filename)

        #create the probe point in vtkPoints format
        pointVTK = vtk.vtkPoints()

        #There is only one point to probe at
        pointVTK.SetNumberOfPoints(1)

        #set the coordinates of the probing point
        pointVTK.InsertPoint(0, probe_x, probe_y, 0.0)

        #probe WSE at the probing point
        points, WSE, elev = vtk_handler.probeUnstructuredGridVTKOnPoints(pointVTK, reader, 'Water_Elev_ft')

        print("WSE = ", WSE)

        probed_WSE[i] = WSE[0]

        #get the water depth at cell centers from the VTK
        water_depth = vtk_handler.get_uGRid_cell_field_with_name(reader, 'Water_Depth_ft')

        if water_depth_all is None:
            water_depth_all = np.zeros((water_depth.shape[0], nSamples))

        water_depth_all[:,i] = water_depth

    #calculate the WSE at some specific exceedance probabilities
    exceedance_probabilities = [99, 90, 50, 10, 1]
    indices = [min(int(pi *(nSamples+1)/100), nSamples-1) for pi in exceedance_probabilities]

    print("probed_WSE = ", probed_WSE)
    print("indices = ", indices)

    probe_WSE_sorted = np.sort(probed_WSE)[::-1]

    #print out the WSE values corresponding to the exceedance probabilities
    WSE_exceedance = []

    for i in indices:
        WSE_exceedance.append(probe_WSE_sorted[i])

    print("WSE_exceedance = ", WSE_exceedance)

    #plot WSE exceedance of probability at monitoring point
    plot_WSE_exceedance_probability(exceedance_probabilities, probe_WSE_sorted)

    #process the water depth at each cell center in the mesh
    water_depth_exceedance_of_probabilities = np.zeros((water_depth_all.shape[0], len(exceedance_probabilities)))

    #loop over all cells
    for iCell in range(water_depth_all.shape[0]):
        depths_at_cell = water_depth_all[iCell,:]

        dephts_at_cell_sorted = np.sort(depths_at_cell)[::-1]

        for i, indx in enumerate(indices):
            water_depth_exceedance_of_probabilities[iCell, i] = dephts_at_cell_sorted[indx]

    #save the cell center water depth exceedance of probability to VTK file
    # Read in base vtk (just use "cases/case_000001.vtk")
    fileName = "cases/case_000001.vtk"
    reader = vtk.vtkUnstructuredGridReader()
    reader.SetFileName(fileName)
    reader.Update()
    mesh = reader.GetOutput()

    # Add data set and write VTK file
    meshNew = dsa.WrapDataObject(mesh)

    for i, exceedance_probability in enumerate(exceedance_probabilities):
        meshNew.CellData.append(water_depth_exceedance_of_probabilities[:,i], "h_"+str(exceedance_probability)+"_percent")

    writer = vtk.vtkUnstructuredGridWriter()
    writer.SetFileName("water_depth_exceedance_of_probabilities.vtk")
    writer.SetInputData(meshNew.VTKObject)
    writer.Write()

    print("Done.")

def plot_WSE_exceedance_probability(exceedance_probabilities, probe_WSE_sorted):
    """
    Plot the WSE exceedance of probability

    Parameters
    ----------
    exceedance_probabilities
    probe_WSE_sorted

    Returns
    -------

    """

    exceedance = np.arange(1.0, len(probe_WSE_sorted)+1) / len(probe_WSE_sorted)

    plt.plot(exceedance*100, probe_WSE_sorted)

    # set the limit for the x and y axes
    plt.ylim([0, 100])
    plt.ylim([min(probe_WSE_sorted), max(probe_WSE_sorted)])

    # set x and y axes label and font size
    plt.xlabel(r'Probability of Exceedence (\%)', fontsize=16)
    plt.ylabel(r'WSE (ft)', fontsize=16)

    # show the ticks on both axes and set the font size
    plt.tick_params(axis='both', which='major', labelsize=12)

    # set axis label format
    plt.gca().xaxis.set_major_formatter(StrMethodFormatter('{x:,.0f}'))
    plt.gca().yaxis.set_major_formatter(StrMethodFormatter('{x:,.2f}'))

    # show title and set font size
    plt.title('WSE exceedance of probability at monitoring point', fontsize=16)

    #save the plot to a file
    plt.savefig("WSE_exceedance_of_probability.png", dpi=300, bbox_inches='tight')

    # show legend, set its location, font size, and turn off the frame
    # plt.legend(loc='lower left', fontsize=14, frameon=False)
    #plt.show()


if __name__ == "__main__":

    pyHMT2D.setVerbose(True)

    #record the start time
    start_time = time.time()

    samples = np.loadtxt("sampledManningN_2022_03_10-10_24_34_PM.dat", delimiter=',')

    # number of samples
    nSamples = samples.shape[0]

    #ID and name of the Manning's n zone whose n value is changes in the Monte Carlo simulations.
    #The ID and name are hard-coded here. Need to modify for a specific case.
    ManningN_MaterialIDs = [2]           #Note: the ID in srhhyro file.
    ManningN_MaterialNames = ['channel']

    #The control file name for the base case
    srhcontrol_file = "Muncie.srhhydro"

    #The Monte Carlo simulations can be run in parallel or in serial.    
    bParallel = True
    if bParallel:
        nProcess = 4   #number of cores to use
        #Monte_Carlo_simulations_parallel(srhcontrol_file, samples, ManningN_MaterialIDs, ManningN_MaterialNames, nProcess=nProcess, bDeleteCaseDir=True)
    else:
        Monte_Carlo_simulations_serial(srhcontrol_file, samples, ManningN_MaterialIDs, ManningN_MaterialNames, bDeleteCaseDir=True)
        #pass

    #postprocess the results
    postprocess_results(nSamples)

    #record the end time
    end_time = time.time()
    
    #print the total time taken in hours
    print("Total time taken: ", (end_time - start_time)/3600, " hours")

    print("All done!")


